### ISSUE TITLE
assertion violated on a diff produced by GNU diff

### ISSUE THREAD

**Issue by cpressey** [ymattw/cdiff#42]
Hello,

I just tried diffing two files (which happened to be completely different) and piping the result into `cdiff` (current master), and it tripped an assertion.  Steps to reproduce (on Ubuntu 14.04 LTS) attached, with some output elided with [...] for brevity:

    % diff --version
    diff (GNU diffutils) 3.3
    [...]
    % wget https://raw.githubusercontent.com/moteus/lua-path/master/lua/path.lua
    % wget https://raw.githubusercontent.com/stevedonovan/Penlight/master/lua/pl/path.lua
    % diff -ru path.lua path.lua.1 | cdiff
    --- path.lua    2014-09-09 13:26:44.921422660 +0100
    +++ path.lua.1  2014-09-09 13:27:22.745423613 +0100
    @@ -1,533 +1,413 @@
    -local pacakge = require "package"
    -local string  = require "string"
    [...]
    -PATH.DIR_SEP    = DIR_SEP
    -PATH.IS_WINDOWS = IS_WINDOWS
    -
    ---
    Traceback (most recent call last):
      File "/home/cpressey/toolshelf/.bin/cdiff", line 7, in <module>
        sys.exit(cdiff.main())
      File "/home/cpressey/toolshelf/github.com/ymattw/cdiff/cdiff.py", line 770, in main
        markup_to_pager(stream, opts)
      File "/home/cpressey/toolshelf/github.com/ymattw/cdiff/cdiff.py", line 631, in markup_to_pager
        for line in color_diff:
      File "/home/cpressey/toolshelf/github.com/ymattw/cdiff/cdiff.py", line 396, in markup
        for diff in diffs:
      File "/home/cpressey/toolshelf/github.com/ymattw/cdiff/cdiff.py", line 374, in get_diff_generator
        assert diff._new_path is not None
    AssertionError

**Comment by ymattw** [comment]
This is now fixed in commit f246c51.
